print("Hello World")
print("nama saya gerald")
print("hobi saya bermain game")
print("saya berumur 15 tahun")
print("saya tinggal di depok")
print("aya sekolah di smk harapan bangsa")
print("saya lahir di depok")
print("makanan favorite saya adalah ayam ")
print("cita cita saya ingin menjadi pengusaha")
print("game kesukaan saya adalah mobile legend")